import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/components/common/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR">
      <body className="font-body-md text-body-md antialiased min-h-screen">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
